### ISSUE TITLE
路由切换时会出现一个textarea

### ISSUE THREAD

**Issue by xxwangkaimin** [tinymce/tinymce-vue#287]
路由切换的时候，富文本编辑器会以一个textarea形式展现

**Comment by jscasca** [comment]
@xxwangkaimin can you make a simple replication in a codesandbox so that we can look into this?

**Comment by sherlock-7717** [comment]
同样的问题

**Comment by citrusjunoss** [comment]
What's the solution to this problem?

**Comment by xxwangkaimin** [comment]
@citrusjunoss 

```html
  <div class="tinymce-box w-full">
    <editor ... />
  </div>
```
```scss
<style lang="scss" scoped>
.tinymce-box {
  :deep(textarea[id^="tiny-vue_"]) {
    display: none;
  }
}
</style>
```
This will solve the problem.
